# Generated by Django 6.0.7 on 2026-07-31 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Izohlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('⭐', '1'), ('⭐⭐', '2'), ('⭐⭐⭐', '3'), ('⭐⭐⭐⭐', '4'), ('⭐⭐⭐⭐⭐', '5')])),
                ('izoh', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='izohchi/')),
                ('kasb', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Twohundered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='200k/')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Batafsil tavsif')),
                ('cover_image', models.ImageField(upload_to='projects/covers/', verbose_name='Asosiy rasm')),
                ('telegram_bot_url', models.URLField(blank=True, null=True, verbose_name='Telegram bot havolasi')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Sayt havolasi')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub kodi havolasi')),
                ('technologies', models.CharField(help_text='Vergul bilan ajratib yozing (masalan: Python, Django, Aiogram)', max_length=255, verbose_name='Ishlatilgan texnologiyalar')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name="Narxi (masalan: 200 000 so'm)")),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bajarilish muddati (masalan: 2 kun)')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatilsinmi?")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatdami?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm tavsifi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.myproject', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
            },
        ),
    ]
